---
title: "Rationale Output"
author: 'Derien W '
date: "Final Project"
output:
  pdf_document:
    toc: yes
    toc_depth: '2'
  html_document:
    toc: yes
    toc_depth: 2
    toc_float: yes
    number_sections: no
    df_print: paged
---

<style type="text/css">
/* Title */
h1.title {
  color: #3A2C29;
  font-size:60px;
  font-weight: bold;
}
/* Level 1 header */
h1 {
  color: #3A2C29;
}
/* Level 2 header */
h2 {
  color: #C9C675;
}
/* Table of contents */
.list-group-item.active, .list-group-item.active:focus, .list-group-item.active:hover {
    z-index: 2;
    color: #fff;
    background-color: #C9C675;
    border-color: #337ab7;
</style>

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```


```{r packages, echo=FALSE}
library(tidyverse)
library(ggplot2)
library(infer)
library(scales)
library(plotrix)
```

```{r echo=FALSE]}
glimpse(SpeedDating)
``` 

```{r echo=FALSE}
#Are men or women more likely to want a second date? Men are!
mode.m <- table(SpeedDating$DecisionM)
names(mode.m)[which(y==max(mode.m))]
mode.m
mode.f <- table(SpeedDating$DecisionF)
names(mode.f)[which(y==max(mode.f))]
mode.f
# 127/276 women say yes to a second date, and 146/276 men say yes to a second date.

#Find percent of men and women who said yes to another  
YesWomen <- SpeedDating %>% 
    group_by(DecisionF == 1) %>% 
    summarise(percent = 100 * n() / nrow(SpeedDating))
YesMen <- SpeedDating %>% 
    group_by(DecisionM == 1) %>% 
    summarise(percent = 100 * n() / nrow(SpeedDating))
YesMen.P <- SpeedDating %>% 
    group_by(DecisionM == 1) %>% 
    summarise(proportion = n() / nrow(SpeedDating))
YesWomen.P <- SpeedDating %>% 
    group_by(DecisionF == 1) %>% 
    summarise(proportion = n() / nrow(SpeedDating))
##Used the numbers from the code above to fill in the values below
df2 <- data.frame(
  group = c("Yes(M)","No(M)", "Yes(W)", "No(W)"),
  value = c(52.89855, 47.10145, 46.01449, 53.98551)
)
## About 53% of men and 46% of women said they would like to go on a second date with a partner. 
ggplot(df2, aes(x=group, y=value)) +
  geom_segment( aes(x=group, xend=group, y=0, yend=value), color="grey") +
  geom_point( color="darkgreen", size=4, alpha=0.6) +
  labs(x = "Men and Women", y = "Percentages" ,title = "Percentages of Men and Women who wanted/didn't want a second date") +
  theme_light() +
  theme(
    panel.grid.major.y = element_blank(),
    panel.border = element_blank(),
    axis.ticks.y = element_blank()
  ) 
```



```{r piechart, echo=FALSE}
## Mens response
dfm <- data.frame(
  group = c("Another date sounds good", "No second date for me"), 
  value = c(53, 47)
  )
pie <- bpm + coord_polar("y", start=0)
pie
## Womens response
dfw <- data.frame(
  group = c("Yes, another date", "No second date for me"), 
  value = c(46, 54)
  )
pie2 <- bpw + coord_polar("y", start=0)
pie2
# The pie charts appear to be inverse a little bit. The amount of men who want another date roughly equals the amount of women who don't want another date, and vice versa.
slices <- c(53, 47, 46, 54) 
lbls <- c("Yes(M)", "No(M)", "Yes(W)", "No(W)")
pie3D(slices,labels=lbls,explode=0.1,
   main="Pie Chart of Decisions made ")
```



```{r echo=FALSE}
#Now that we know the percentages of men and women that would like to go on a second date, let's find out what the other person estimates that their date would like another using PartnerYes
PF <- SpeedDating %>% 
    group_by(PartnerYesF) %>% 
    summarise(percent = 100 * n() / nrow(SpeedDating))
PF
PM <- SpeedDating %>% 
    group_by(PartnerYesM) %>% 
    summarise(percent = 100 * n() / nrow(SpeedDating))
PM
# Only roughly 5% of women estimated that their date would have a 10/10 chance of wanting another date! While only 3.6% of men thought their date would definitely want another!
PFBar <- data.frame(
  rating=c("1-2","3-4","5-6","7-8","9-10") ,  
  value=c(10.14,9.02,39.83,28.25,12.66)
  )
# Plot showing distribution of the estimation of wanting a second date for women
ggplot(PFBar, aes(x=rating, y=value)) +
  geom_segment( aes(x=rating, xend=rating, y=0, yend=value), color="grey") +
  geom_point( color="red", size=4, alpha=0.6) +
  labs(title = "Distribution of the estimation of wanting a second date for women") +
  theme_light() +
  coord_flip() +
  theme(
    panel.grid.major.y = element_blank(),
    panel.border = element_blank(),
    axis.ticks.y = element_blank()
  )
PMBar <- data.frame(
  rating=c("1-2","3-4","5-6","7-8","9-10") ,  
  value=c(9.77,13.76,37.31,28.97,10.13)
) 
# Plot showing distribution of the estimation of wanting a second date for men
ggplot(PMBar, aes(x=rating, y=value)) +
  geom_segment( aes(x=rating, xend=rating, y=0, yend=value), color="grey") +
  geom_point( color="blue", size=4, alpha=0.6) +
  labs(title = "Distribution of the estimation of wanting a second date for men") +
  theme_light() +
  coord_flip() +
  theme(
    panel.grid.major.y = element_blank(),
    panel.border = element_blank(),
    axis.ticks.y = element_blank()
  )
```



```{r echo=FALSE}
#First, let's see the amount of men and women of each race
ggplot(data=SpeedDating, mapping=aes(x=RaceM)) +
  geom_histogram(color="black", fill="darkgreen", stat ="count", binwidth=5) +
  labs(x="Race", y="Frequency", 
       title="Distribution of men in each race")
ggplot(data=SpeedDating, mapping=aes(x=RaceF)) +
  geom_histogram(color="black", fill="blue", stat ="count", binwidth=5) +
  labs(x="Race", y="Frequency", 
       title="Distribution of women in each race")
MRace <- SpeedDating %>% 
  group_by(RaceM) %>%
  summarize(count = n())
FRace <- SpeedDating %>% 
  group_by(RaceF) %>%
  summarize(count = n())
FRace
MRace


#The data set tends is unevenly distributed for each race which could lead to biases in data

```


```{r include=FALSE}
options(dplyr.summarise.inform = FALSE)
decm <- SpeedDating %>%
  filter(DecisionM == 1) %>%
   group_by(RaceM, RaceF) %>%
  summarize(count = n())

decf <- SpeedDating %>%
  filter(DecisionF == 1) %>%
   group_by(RaceF, RaceM) %>%
  summarize(count = n())

x.decm <- decm %>%
  mutate(Decision = "Males")

x.decf <- decf %>%
  mutate(Decision = "Females")

preference <- rbind(x.decm, x.decf)
preference
```


```{r plots include=FALSE}
RaceMPlot<- ggplot(preference, aes(x = RaceM, y = count)) +
  geom_bar(
    aes(colour = as.factor(Decision)),
    stat = "identity", pos = "dodge",
    width = 0.7
    ) +
  labs(x = "Males", y = "Count" ,title = "Ethnic Dating for Men") +
  scale_color_manual(values = c("#0073C2FF", "#EFC000FF"))+ 
  scale_fill_manual(values = c("#0073C2FF", "#EFC000FF")) 
RaceMPlot

RaceFPlot <- ggplot(preference, aes(x = RaceF, y = count)) +
  geom_bar(
    aes(colour = as.factor(Decision)),
    stat = "identity", pos = "dodge",
    width = 0.7
    ) +
  labs(x = "Females", y = "Count" ,title = "Ethnic Dating for Women")+
  scale_color_manual(values = c("#0073C2FF", "#EFC000FF"))+
  scale_fill_manual(values = c("#0073C2FF", "#EFC000FF")) 
RaceFPlot
``` 

```{r DUMP, include=FALSE}
bpm <- ggplot(dfm, aes(x="Percent of men", y=value, fill=group))+
geom_bar(width = 1, stat = "identity")
bpm
bpw <- ggplot(dfw, aes(x="Percent of women", y=value, fill=group))+
geom_bar(width = 1, stat = "identity")
bpw
YesMen
YesWomen
YesMen.P
YesWomen.P
test1 <- SpeedDating %>%
  filter(DecisionM == 1 & DecisionF == 1) %>%
   group_by(RaceF, RaceM) %>%
  summarize(count = n())
test1
```
## References
1. https://ggplot2.tidyverse.org/reference/geom_histogram.html
2. https://ggplot2.tidyverse.org/reference/geom_bar.html
3. https://www.statmethods.net/graphs/pie.html
4. https://www.r-graph-gallery.com/index.html
5. https://dplyr.tidyverse.org/reference/group_by.html
6. http://www.sthda.com/english/articles/32-r-graphics-essentials/132-plot-grouped-data-box-plot-bar-plot-and-more/



